### PR TITLE
feat: Add `x/bank` account balance and `x/staking` delegations/redelegations/unbonding delegations

### PR DESCRIPTION
**Pull request by huichiaotsou**

### CODE REVIEW

**Comment by ankurdotb** [comment]
@huichiaotsou On our default branch, I pulled in all changes from upstream base, but I see a lot of commits in this PR that are NOT in the base. Is this intentional/meant to be made available upstream in BDJuno?

**Comment by huichiaotsou** [comment]
@ankurdotb those commits I made are for the top account page as requested. I think you can safely merge the latest commits from upstream without issue. There should not be conflicts.

**Comment by ankurdotb** [comment]
@huichiaotsou Thanks, yes I can see there should be no issues with merging. I guess the question that I'm thinking of is that originally, BDJuno used to index and store account as well as delegation balances in Postgres database + had GraphQL queries.

In BDJuno v2 (or v3?) this was switched to have account, delegations, etc balances NOT stored in Postgres and queried directly from the node RPC/gRPC endpoints using GraphQL Hasura Actions. I imagine this change was made for performance reasons, or was there a different reason? Trying to understand why that switch was made, so that I can understand the implications (e.g., is there a performance impact etc).

Let me know if it's easier to have a call or chat this through perhaps.

**Comment by huichiaotsou** [comment]
Hey @ankurdotb sorry I missed your message. Yes those were removed and moved to node query because of performance, for chains that have 100+ txs per block.

**Pull request closed without merging**
